### ISSUE TITLE
The error encountered was: '401 Client Error: Unauthorized'

### ISSUE THREAD

**Issue by t-power89** [NicoSantangelo/sublime-text-trello#10]
Hi  there, very nice idea really appreciate it. I installed the plug in via package control then got to the site https://trello.com/1/connect?... to get my ket. Got it and then i went to preferences>package settings> trello>setting user> and passed the stuff below: 

{
    "key"   : "",
    "secret": "",
    "token" : "{THE TOKEN I GOT FROM THE WEB PAGE PASED HERE}"
}

Saved. And then tried to do Trello:Navigate but i keep getting the error "The error encountered was: '401 Client Error: Unauthorized'"" . I tried to copy and paste the token again as suggested but the same error appears. Am i doing something wrong? (I m very new to sublime)

**Comment by t-power89** [comment]
Ok i found the issue. I had to copy and paste all the default settings into the user settings and then edit the token bit (I just coping and editing that part only). Thanks again

**Comment by nicosantangelo** [comment]
Sorry I didn't get to you sooner but glad you figured it out!
I'll close this but feel free to @ me if you need anything else
